FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm config set fetch-retries 5 \
    && pnpm config set fetch-timeout 600000 \
    && pnpm config set network-concurrency 4
RUN pnpm install

COPY . .

RUN pnpm nx build api-v2 --configuration=production

FROM node:20-alpine AS runner
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate


COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/apps/api-v2/dist ./dist

EXPOSE 4000

CMD ["node", "dist/main.js"]
