FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm config set fetch-retries 5 \
    && pnpm config set fetch-timeout 600000 \
    && pnpm config set network-concurrency 4
RUN pnpm install

COPY . .

RUN pnpm nx build shop-v2 --configuration=production


FROM node:20-alpine AS runner
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

ENV NODE_ENV=production

COPY --from=builder /app/dist/apps/shop-v2/.next/standalone ./
COPY --from=builder /app/dist/apps/shop-v2/.next/static ./.next/static
COPY --from=builder /app/dist/apps/shop-v2/public ./public

EXPOSE 3000

CMD ["node", "apps/shop-v2/server.js"]
