import './page.css';

export const metadata = {
  title: 'Welcome to shop-v2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <header className="app-header">
            <div className="header-content">
              <h1 className="app-title">Nx Shop Demo</h1>
            </div>
          </header>

          <main className="app-main">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
